version: '3.8'
services:
  # Enable NATS jetstream when I have two services up and running
  nats:
    image: nats
    expose:
      - "4222"
    command: --js
    ports:
      - 4222:4222
      - 6222:6222 
      - 8222:8222
  # nginx:
  #   depends_on:
  #     - api
  #     - client
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./nginx
  #   ports:
  #     - '3050:80'
  #   restart: always
  # client:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./client
  #   volumes:
  #     - ./client:/app
  #     - /app/node_modules
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - 'auth'
  auth:
    build:
      dockerfile: Dockerfile.dev
      context: ./auth
    env_file:
      - ./auth/.env.dev
    volumes:
      - ./auth:/app
    ports:
      - '8000:8000'
  mail:
    build:
      dockerfile: Dockerfile.dev
      context: ./mail
    env_file:
      - './mail/.env.dev'
    volumes:
      - ./mail:/app
    ports:
      - '8001:8001'