FROM golang:alpine

ENV GIN_MODE=debug
ENV CGO_ENABLED=1

RUN apk add build-base

WORKDIR /app

COPY . .

RUN go get github.com/githubnemo/CompileDaemon

ENTRYPOINT CompileDaemon --build="go build main.go" --command=./main